{% set name = "conda-merge" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 83f6bd5f1742b99cdb77638fdc19e82d826d8f3993c1dc9b8c7951a3b368e2f5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - conda-merge = conda_merge:main

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - pip
    - pyyaml

test:
  commands:
    - conda-merge --help
    - pip check

about:
  home: https://github.com/amitbeka/conda-merge
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tool to merge environment files of the conda package manager

  description: |
    Tool for merging Conda (Anaconda) environment files into one file. 
    This is used to merge your application environment file with any 
    other environment file you might need (e.g. unit-tests, debugging, 
    jupyter notebooks) and create a consistent environment without 
    breaking dependencies from the previous environment files.
  doc_url: https://github.com/amitbeka/conda-merge
  dev_url: https://github.com/amitbeka/conda-merge

extra:
  recipe-maintainers:
    - jan-janssen
