{% set name = "conda-merge" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 532f5246f143f82aaa4f2698a0b65dfd04bbb691a106cd8ac2613c1b6f25f3fc

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - conda-merge = conda_merge:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pip
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  commands:
    - conda-merge --help
    - pip check

about:
  home: https://github.com/amitbeka/conda-merge
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tool to merge environment files of the conda package manager

  description: |
    Tool for merging Conda (Anaconda) environment files into one file. 
    This is used to merge your application environment file with any 
    other environment file you might need (e.g. unit-tests, debugging, 
    jupyter notebooks) and create a consistent environment without 
    breaking dependencies from the previous environment files.
  doc_url: https://github.com/amitbeka/conda-merge
  dev_url: https://github.com/amitbeka/conda-merge

extra:
  recipe-maintainers:
    - jan-janssen
